---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeting-service
  labels:
    app: greeting-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
      - name: greeting-service
        image: nhatthai/greeting-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8899
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting-service
spec:
  type: NodePort
  ports:
  - port: 8899
    targetPort: 8899
    nodePort: 31999
  selector:
    app: greeting-service
