---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: name-service
  labels:
    app: name-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: name-service
    spec:
      containers:
      - name: name-service
        image: nhatthai/name-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: name-service
  labels:
    app: name-service
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 31890
  selector:
    app: name-service
